import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart';
import 'package:web3dart/web3dart.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String? _mood;
  final TextEditingController _controller = TextEditingController();

  //Used to make network calls by the Web3 dart library
   Client httpClient=Client();

   //Web3 class that sends the request to the Ethereum network
  late Web3Client web3Client;
  final metamaskAddress = 'Input your metamask Rospen account address';

  @override
  void initState() {
    web3Client = Web3Client('Infura Ropsten Api endpint',
        httpClient);
    geMood(metamaskAddress);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Column(
        mainAxisSize: MainAxisSize.max,
        ma
        children: [
          Center(child: Text(_mood ?? 'No Mood Yet')),
          const Spacer(flex: 1,),
          Align(
            alignment: Alignment.bottomCenter,
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _controller,
                    decoration: InputDecoration(
                      fillColor: Colors.grey,
                        border: OutlineInputBorder(
                          borderSide: BorderSide(color: Theme.of(context).primaryColor,width: 2),
                            borderRadius:
                                BorderRadius.all(Radius.circular(5)))),
                  ),
                ),
                IconButton(
                    onPressed: () async {
                      var res =await setMood('setMood', [_controller.text]);
                      print(res);
                      geMood(metamaskAddress);
                    },
                    icon: const Icon(Icons.send))
              ],
            ),
          )
        ],
      ),
    );
  }

  Future<DeployedContract> loadContract() async {
    //loads the ABI json file from assets and converts it into a String
    String abi = await rootBundle.loadString('assets/abi.json');
    //Get the contract address from the Deploy tab on Remix IDE
    String contractAddress = 'Input the contract addres from Remix';
    //Pass in the json String and the name of the smart contract class.
    //in this scenario the name of our contract class is MoodDiary
    //Also pass in the Ethereum address which is generated by the utility class from web3 dart libray which 
    //needs you to pass in the contract address
    final contract = DeployedContract(ContractAbi.fromJson(abi, 'MoodDiary'),
        EthereumAddress.fromHex(contractAddress));
    return contract;
  }

  Future<List<dynamic>> query(String functionName, List<dynamic> args) async {
    //loads the contract
    final contract = await loadContract();
    //Find the function we want from the contract abi
    final ethFunction = contract.function(functionName);
    //Call the contract on the Ethereum Rospen test network and return its result
    final result = await web3Client.call(
        contract: contract, function: ethFunction, params: args);
    return result;
  }

  Future<String> setMood(String functionName, List<dynamic> args) async {
    EthPrivateKey credential = EthPrivateKey.fromHex(
        'Your Metamask Rospen Account Private Key');//Dont share this with anyone
    final contract = await loadContract();
    final ethFunction = contract.function(functionName);
    //Sends the transaction to the Ethereum network and returns a hash of the mined transaction
    final result = await web3Client.sendTransaction(
        credential,
            //create a transaction using the web3 utility class which is sent on to the Ethereum netwok to be mined
        Transaction.callContract(
          contract: contract,
          function: ethFunction,
          parameters: args,
        ),
        //The chain Id represents the Ethereum network we are operating on.
        //In this case Rospen net testnet whose id is 3,others include rinkeby whose id is 4 etc
        chainId: 3);
    return result;
  }

  Future<void> geMood(var address) async {
    List<dynamic> res = await query('getMood', []);
    print(res);
    res.forEach((element) {
      _mood = element;
    });
    setState(() {});
  }
}
